{
 "title": "Dashboard OLT ZTE C3x (Geral)",
 "description": "Desenvolvido por: Autor: Fernando Almondes\nData: 08/03/2025 - 14:43\nVersão: v4 (Geral)",
 "tags": [
  "olt",
  "gpon"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "OLT",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center> <a target=\"new_blank\" href=\"https://beesolutions.com.br\"><img style=\" width=\"100\" height=\"80\" \" src=\"https://beesolutions.com.br/static/home/images/bee/so-logo.png\"> <p> <h5></h5> </a> </center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs Autorizadas" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1077",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1078",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Autorizadas" ],
       "text": "setAlias(Total Autorizadas)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Autorizadas" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs Online" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1106",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1107",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Onlines" ],
       "text": "setAlias(Total Onlines)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Onlines" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs LOS" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1048",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1049",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total LOS" ],
       "text": "setAlias(Total LOS)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs LOS" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs Dying Gasp" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1164",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONUs Dying Gasp" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs Offline" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1957",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1958",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Offlines" ],
       "text": "setAlias(Total Offlines)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs OFF" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "Temperatura das Placas" },
     "itemTag": { "filter": "Temperatura" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "uptime" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1021",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: U/",
        "U"
       ],
       "text": "replaceAlias(/$host: U/, U)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Uptime/" },
     "itemTag": { "filter": "Uptime" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Visão Geral de Cards",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "zabbix",
     "rawSql": "SELECT SUBSTRING_INDEX(i.name, ':', 1) AS placa, MAX(CASE WHEN i.name LIKE '%Uso de CPU%' THEN hu.value END) AS cpu, MAX(CASE WHEN i.name LIKE '%Uso de Mem%' THEN hu.value END) AS memoria, MAX(CASE WHEN i.name LIKE '%Status Operac%' THEN hu.value END) AS status, DATE_FORMAT(FROM_UNIXTIME(MAX(hu.clock)), '%d-%m-%Y %H:%i:%s') AS ultima_verificacao FROM items i JOIN hosts h ON h.hostid = i.hostid JOIN history_uint hu ON hu.itemid = i.itemid WHERE i.flags = 4 AND i.status = 0 AND h.status = 0 AND h.host = '$host' AND i.key_ LIKE 'netstream.zte.card.%' AND hu.clock = ( SELECT MAX(clock) FROM history_uint WHERE itemid = i.itemid AND clock > UNIX_TIMESTAMP() - 3600 ) GROUP BY placa ORDER BY placa;"
    }
   ]
  },
  {
   "title": "Visão Geral por PON",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select SUBSTRING_INDEX(it.name, ' - ', 1) as name, MAX(CASE WHEN it.name LIKE '% - ONUs Autorizadas' THEN hu.value END) AS Autorizadas, MAX(CASE WHEN it.name LIKE '% - ONUs Online' THEN hu.value END) AS Onlines, MAX(CASE WHEN it.name LIKE '% - ONUs Offline' THEN hu.value END) AS Offlines, MAX(CASE WHEN it.name LIKE '% - LOS%' THEN hu.value END) AS LOS, MAX(CASE WHEN it.name LIKE '% - DyingGasp%' THEN hu.value END) AS DyingGasp, DATE_FORMAT(CONVERT_TZ(FROM_UNIXTIME(MAX(hu.clock)), '+03:00', '+03:00'), '%d-%m-%Y %H:%i:%s') AS ultima_verificacao from items it left join (select itemid, max(clock) as max_clock from history_uint group by itemid) as max_hu on it.itemid = max_hu.itemid left join history_uint hu on hu.itemid = max_hu.itemid and hu.clock = max_hu.max_clock inner join hosts ht on ht.hostid = it.hostid where it.flags in (0,4) and it.status = 0 and ht.status = 0 and ht.host in ('$host') and it.name LIKE 'PON %' and (it.name LIKE '% - ONUs Autorizadas' OR it.name LIKE '% - ONUs Online' OR it.name LIKE '% - ONUs Offline' OR it.name LIKE '% - LOS%' OR it.name LIKE '% - DyingGasp%') group by SUBSTRING_INDEX(it.name, ' - ', 1) order by name;"
    }
   ]
  },
  {
   "title": "Historico de ONUs Onlines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "ONUs Online" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        ""
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Onlines" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Los",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "application": { "filter": "ONUs LOS" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        ""
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs LOS" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Energia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "application": { "filter": "ONUs Dying Gasp" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        ""
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs DyingGasp" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Offlines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "application": { "filter": "ONUs Offline" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        ""
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs OFF" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Análise de Interfaces (Uplinks)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "zabbix",
     "rawSql": "SELECT sub.host, sub.interface, sub.bitsin, sub.bitsout, sub.status, sub.speed, sub.usoin, sub.usoout, sub.rxpower, sub.txpower, sub.distancia, sub.limiterx, CASE WHEN sub.rxpower IS NULL THEN NULL WHEN sub.is_xgei = 1 AND (sub.rxpower < -9.00 OR sub.rxpower > 0.00) THEN 'anormal' WHEN sub.is_xgei = 0 AND (sub.rxpower < -11.00 OR sub.rxpower > -1.00) THEN 'anormal' END AS staturx, sub.ultverificacao FROM ( SELECT ht.name AS host, SUBSTRING_INDEX(it.name, ': ', 1) AS interface, MAX(CASE WHEN it.name LIKE '%Trafego de Entrada%' THEN h.value END) AS bitsin, MAX(CASE WHEN it.name LIKE '%Trafego de Saida%' THEN h.value END) AS bitsout, MAX(CASE WHEN it.name LIKE '%Status Operacional%' THEN h.value END) AS status, MAX(CASE WHEN it.name LIKE '%Velocidade da Porta%' THEN h.value END) AS speed, MAX(CASE WHEN it.name LIKE '%Trafego de Entrada%' THEN h.value END) / NULLIF(MAX(CASE WHEN it.name LIKE '%Velocidade da Porta%' THEN h.value END), 0) * 100 AS usoin, MAX(CASE WHEN it.name LIKE '%Trafego de Saida%' THEN h.value END) / NULLIF(MAX(CASE WHEN it.name LIKE '%Velocidade da Porta%' THEN h.value END), 0) * 100 AS usoout, MAX(CASE WHEN it.name LIKE '%Sinal RX%' THEN h.value END) AS rxpower, MAX(CASE WHEN it.name LIKE '%Sinal TX%' THEN h.value END) AS txpower, NULL AS distancia, MAX(CASE WHEN it.name LIKE '%xgei%' THEN '0.00 a -9.00' WHEN it.name LIKE '% gei_%' THEN '-1.00 a -11.00' END) AS limiterx, MAX(CASE WHEN it.name LIKE '%xgei%' THEN 1 ELSE 0 END) AS is_xgei, MAX(DATE_FORMAT(CONVERT_TZ(FROM_UNIXTIME(h.clock), '+00:00', '+00:00'), '%d-%m-%Y %H:%i:%s')) AS ultverificacao FROM items it INNER JOIN hosts ht ON ht.hostid = it.hostid AND ht.name IN ('$host') AND ht.status = 0 LEFT JOIN ( SELECT itemid, MAX(clock) AS max_clock FROM history WHERE clock > UNIX_TIMESTAMP() - 7200 GROUP BY itemid ) AS max_h ON it.itemid = max_h.itemid LEFT JOIN history h ON h.itemid = max_h.itemid AND h.clock = max_h.max_clock INNER JOIN items_applications ia2 ON ia2.itemid = it.itemid INNER JOIN applications ap ON ap.applicationid = ia2.applicationid AND ap.name = 'Uplink / LAN OLT' WHERE it.flags IN (0, 4) AND it.status = 0 AND ( it.name LIKE '%Trafego%' OR it.name LIKE '%Status Operacional%' OR it.name LIKE '%Velocidade da Porta%' OR it.name LIKE '%Erros%' OR it.name LIKE '%Drops%' OR it.name LIKE '%Sinal RX%' OR it.name LIKE '%Sinal TX%' ) GROUP BY interface, host ) sub ORDER BY sub.interface;"
    }
   ]
  },
  {
   "title": "Tráfego das Interfaces de Uplink",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "Uplink / LAN OLT" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:1818",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: I/",
        "I"
       ],
       "text": "replaceAlias(/$host: I/, I)"
      }
     ],
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Network Interfaces Bits" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tráfego das Portas PON (GPON)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Porta .* Trafego/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Painel de Incidentes - OLT",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT-NETSTREAM" },
     "host": { "filter": "$host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}